## GET ALL DISTINCT IDs

SELECT id FROM friday
UNION
SELECT id FROM saturday
UNION
SELECT id FROM sunday
ORDER BY id ASC


## JSON PER DAY

SELECT DISTINCT id FROM friday ORDER BY id ASC

SELECT DISTINCT id FROM saturday ORDER BY id ASC

SELECT DISTINCT id FROM sunday ORDER BY id ASC